### PR TITLE
Transcoding to tif with ffmpeg

### PR DESCRIPTION
**Pull request by sevein**
Connects to https://github.com/archivematica/Issues/issues/91.

### CODE REVIEW

**Comment by ablwr** [comment]
This is ready for review. Or should I squash first?

I tested this locally and everything migrates fine and it runs well with our non-corrupt test jp2s in our test suite. There are some jpeg2000 files with other extensions... they currently don't get normalized and they don't get normalized in this either, only the .jp2 extension.

**Comment by sevein** [comment]
Thank you!

@ablwr can you add a short description inside the migration? We still have that TODO there.

Once you're done with that yeah I'd suggest to squash and merge! You may want to release today (and bump `__version__`) or wait until PRONOM v94, your call! :D :D

**Comment by sevein** [comment]
I think that you should be author of the commit by the way, you did the hard work. You can add me as a co-author if you want - see https://help.github.com/articles/creating-a-commit-with-multiple-authors/.

**Comment by ablwr** [comment]
Ahhhh forgot about that, will do.

**Comment by ablwr** [comment]
YOU did the hard work!!!

**Comment by sevein** [comment]
FYI I can't approve because I submitted the PR. But I 👍!!!

**Review by ablwr — APPROVED** [review]

**Comment by ablwr** [comment]
I apparently need more code review points, according to my Github analysis/ ;) So I left you as author and me as co-author.

**Comment by sevein** [comment]
image
is that an acorn???

**Pull request merged**
