### PR TITLE
Migrations: update id{tool,command}s

### PR DESCRIPTION
**Pull request by sevein**
This is a sequel of #58. It updates two tools:
- Update fido to 1.3.7
- Update siegfried to 1.7.6

Also, two extra commits in order to:
- Bump `__version__` to `1.7.2` (needed for the release)
- It fixes a bug in pronom_92.json (delete pks)

---

Before this PR:

```
> m.IDTool.objects.all().values_list()

[
    (1, u'115bc526-c75b-4d2a-9fb9-090c5b49620f', u'File Extension', u'0.1', True, u'file-extension-01'),
    (2, u'8f04f36d-8d43-43c2-92f9-da64c5530106', u'Fido', u'1', False, u'fido-1'),
    (3, u'ea5274a2-9866-439c-a68c-5c8aadf6d3cd', u'Siegfried', u'1.0.0', False, u'siegfried-100'),
    (4, u'c33c9d4d-121f-4db1-aa31-3d248c705e44', u'Fido', u'1.3.6', True, u'fido-134'),
    (5, u'454df69d-5cc0-49fc-93e4-6fbb6ac659e7', u'Siegfried', u'1.7.3', True, u'siegfried-150')
]

> m.IDCommand.objects.all().values_list('id', 'uuid', 'description', 'tool', 'enabled')

[
    (1, u'41efbe1b-3fc7-4b24-9290-d0fb5d0ea9e9', u'Identify by File Extension', u'115bc526-c75b-4d2a-9fb9-090c5b49620f', True),
    (2, u'1c7dd02f-dfd8-46cb-af68-5b305aea1d6e', u'Identify using Fido', u'8f04f36d-8d43-43c2-92f9-da64c5530106', False),
    (3, u'a8e45bc1-eb35-4545-885c-dd552f1fde9a', u'Identify using Fido', u'8f04f36d-8d43-43c2-92f9-da64c5530106', True),
    (4, u'8cc792b4-362d-4002-8981-a4e808c04b24', u'Identify using Siegfried', u'ea5274a2-9866-439c-a68c-5c8aadf6d3cd', False),
    (5, u'9d2cefc1-2bd2-44e4-8d55-6cf8151eecff', u'Identify using Siegfried', u'454df69d-5cc0-49fc-93e4-6fbb6ac659e7', True)
]
```

After this PR:

```
m.IDTool.objects.all().values_list()

[
    (1, u'115bc526-c75b-4d2a-9fb9-090c5b49620f', u'File Extension', u'0.1', True, u'file-extension-01'),
    (2, u'8f04f36d-8d43-43c2-92f9-da64c5530106', u'Fido', u'1', False, u'fido-1'),
    (3, u'ea5274a2-9866-439c-a68c-5c8aadf6d3cd', u'Siegfried', u'1.0.0', False, u'siegfried-100'),
    (4, u'c33c9d4d-121f-4db1-aa31-3d248c705e44', u'Fido', u'1.3.7', True, u'fido-137'),
    (5, u'454df69d-5cc0-49fc-93e4-6fbb6ac659e7', u'Siegfried', u'1.7.6', True, u'siegfried-176')
]

m.IDCommand.objects.all().values_list('id', 'uuid', 'description', 'tool', 'enabled')

[
    (1, u'41efbe1b-3fc7-4b24-9290-d0fb5d0ea9e9', u'Identify by File Extension', u'115bc526-c75b-4d2a-9fb9-090c5b49620f', True),
    (2, u'1c7dd02f-dfd8-46cb-af68-5b305aea1d6e', u'Identify using Fido', u'8f04f36d-8d43-43c2-92f9-da64c5530106', False),
    (3, u'a8e45bc1-eb35-4545-885c-dd552f1fde9a', u'Identify using Fido', u'8f04f36d-8d43-43c2-92f9-da64c5530106', False),
    (6, u'76006ad7-a401-48f6-98f6-2efc01003276', u'Identify using Fido', u'c33c9d4d-121f-4db1-aa31-3d248c705e44', True),
    (4, u'8cc792b4-362d-4002-8981-a4e808c04b24', u'Identify using Siegfried', u'ea5274a2-9866-439c-a68c-5c8aadf6d3cd', False),
    (5, u'9d2cefc1-2bd2-44e4-8d55-6cf8151eecff', u'Identify using Siegfried', u'454df69d-5cc0-49fc-93e4-6fbb6ac659e7', False),
    (7, u'df074736-e2f7-4102-b25d-569c099d410c', u'Identify using Siegfried', u'454df69d-5cc0-49fc-93e4-6fbb6ac659e7', True)
]
```

---

This was done before in the following migrations but only IDTools were updated.
- [0005_update_tool_versions.py](https://github.com/artefactual/archivematica-fpr-admin/blob/qa/1.x/fpr/migrations/0005_update_tool_versions.py)
- [0010_update_fido_136.py](https://github.com/artefactual/archivematica-fpr-admin/blob/qa/1.x/fpr/migrations/0010_update_fido_136.py)

I see three options:
1.  Do the same as 0005 and 0010 - just update the IDTools.
2. Update tools, add new commands - that's what this PR does atm.
3. Replace both tools and commands - seems ideal.

---

Once this is merged we need to make sure that:
- ~archivematica-fpr-admin 1.7.2 is released~
- ~fido: archivematica to bundle fido 1.3.7 (https://github.com/artefactual/archivematica/pull/765)~
- ~archivematica 1.7 (dashboard, mcpclient) adds archivematica-fpr-admin 1.7.2 to requirements~
- ~siegfried: compose/ansible/pkgs(trusty,xenial,centos7) to bundle siegfried 1.7.6~ (not fixed atm but reported)

### CODE REVIEW

**Comment by sevein** [comment]
@jhsimpson can you make sure that the migration is doing the right thing? I've created new commands but I'm not sure if I'm also supposed to create new tools or repurpose the existing ones.

If you want to see it in action there is no need to involve AM at all, just build the testproject/ locally following these instructions: https://github.com/artefactual/archivematica-fpr-admin/blob/qa/1.x/DEVELOPMENT.md.

**Comment by jrwdunham** [comment]
Looks like the following two objects need to be removed from migrations/pronom_92.json because these formats are already in the db from initial_data.json:

    {
        "fields": {
            "slug": "wordperfect-graphics-metafile",
            "group": "fdf9e267-a18c-46a4-a162-b81bcba6322f",
            "uuid": "9b3f9406-a375-4b66-9081-61a317e68cbf",
            "description": "WordPerfect Graphics Metafile"
        },
        "model": "fpr.format"
    },
    {
        "fields": {
            "slug": "verity-collection-stop-list",
            "group": "57361413-1c3b-405d-a9c0-7d3ea381090e",
            "uuid": "d4bfbd9b-15fc-4992-98cb-7cea13879307",
            "description": "Verity Collection Stop List"
        },
        "model": "fpr.format"
    }

If the above need to be changed, I think that that needs to happen in migrations/0015_pronom_92.py.

**Comment by sevein** [comment]
Good catch, @jrwdunham. For some reason I ran into a bunch of extra items that already existed.
Here's the list of elements that I had to delete from the fixture and manage as a Python migration: https://gist.github.com/sevein/03f229fd76fb7af08b8b6c6926320e87. Thank you!

**Review by jrwdunham — APPROVED** [review]
I was able to successfully follow the instructions at https://github.com/artefactual/archivematica-fpr-admin/blob/qa/1.x/DEVELOPMENT.md and explore the FPR GUI and see the expected changes.

**Comment by sevein** [comment]
Thank you! Let's hope that d32bf02 doesn't break user upgrades. I'm assuming if that's the case it should be detected during QA.

**Pull request merged**
