### PR TITLE
remove pks from pronom_88 fixture

### PR DESCRIPTION
**Pull request by jhsimpson**
setting pk's in this fixture causes loaddata to overwrite existing data.

see issue #46

### CODE REVIEW

**Comment by sevein** [comment]
@jhsimpson FYI in the future you can make use of the special GH keywords in the commit message to close the related issue automatically. See https://help.github.com/articles/closing-issues-via-commit-messages/.

**Review by sevein — APPROVED** [review]

**Comment by sevein** [comment]
Should the milestone be 1.2.1? :)

**Comment by jhsimpson** [comment]
This was also merged into stable/1.2.x

**Comment by sevein** [comment]
In qa/1.x: 373642f2f9a7dfe14b95ba974acb5e3e89953fe5.

**Pull request merged**
