### PR TITLE
FPCommand: convert newlines before saving

### PR DESCRIPTION
**Pull request by mistydemeo**
Commands submitted via the web form may end up with \r\n newlines, which breaks bash scripts. This converts \r\n to \n at the time the data is saved to the database.

Fixes #6512.

### CODE REVIEW

**Comment by Hwesta** [comment]
Looks good

**Comment by mistydemeo** [comment]
Looks like this is, in fact, the documented behaviour: https://code.djangoproject.com/ticket/19251

The tl;dr version is that Django does not normalize newlines from form input. Web browsers _typically_ send \r\n.

**Comment by mistydemeo** [comment]
Realized this snuck into yesterday's merge.

**Comment by Hwesta** [comment]
Oops, oh well. The more Django-ish way to do this would be a `clean_command` method (https://docs.djangoproject.com/en/1.5/ref/forms/validation/#cleaning-a-specific-field-attribute) on the FPCommandForm.  Should we do this on IDCommandForm as well?  In future if we find ourselves doing that a lot, maybe a custom form field?

**Pull request closed without merging**
