### PR TITLE
FPR: Add validation rule purpose & command usage

### PR DESCRIPTION
**Pull request by Hwesta**
Add validation to the FPR for rules and commands.

Also, some cleanup to make adding purposes easier.

### CODE REVIEW

**Comment by jhsimpson** [comment]
Looks like PURPOSE_CHOICES was only referenced in one place, and that is gone now, so maybe its definition should/could be removed?

**Comment by mistydemeo** [comment]
:thumbsup:

**Comment by Hwesta** [comment]
`PURPOSE_CHOICES` is passed into the `FPRule.purpose` field as the choices parameter, which was the original usage of the constant.

**Comment by jhsimpson** [comment]
ok, I missed that.  

:thumbsup:

**Pull request merged**
