### PR TITLE
Migrations: PRONOM 90

### LINKED ISSUE #45: Problem: PRONOM90 is missing

### PR DESCRIPTION
**Pull request by sevein**
Update for PRONOM 90 - this closes #45 and replaces #37.

Also includes a fix for #51 in commit `Bump version number to 1.6.1`.

### CODE REVIEW

**Comment by jhsimpson** [comment]
I tried got an error when trying to run the django migration from this branch:

```python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: django_forms_bootstrap, staticfiles, messages, webdesign, accounts, installer, mcp
  Apply all migrations: sessions, administration, tastypie, auth, contenttypes, fpr, main
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying fpr.0009_pronom_90...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 112, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/archivematica/archivematica/src/dashboard/src/fpr/migrations/0009_pronom_90.py", line 12, in data_migration
    Format.objects.create(description="Jamcracker Tracker Module", group_id="00abbdd0-51b3-4162-b93a-45deb4ed8654", uuid="d364de7c-f0b7-44b0-9adc-f5fd248b1c1b")
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 973, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 931, in as_sql
    for obj in self.query.objs
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/autoslug/fields.py", line 221, in pre_save
    slug = instance._meta.module_name
AttributeError: 'Options' object has no attribute 'module_name'`
```

**Comment by sevein** [comment]
`requirements.txt` has changed, you need to update.

**Comment by sevein** [comment]
It seems we're using django-autoslug 1.7.1 in archivematica.git, I guess it needs to be updated too.

**Comment by sevein** [comment]
I don't think AM 1.6.1 should include a fpr-admin release with this PR because of the need for updating django-autoslug to 1.9.3 which generates new migrations as we can't include new migrations in Archivematica until 1.7 is released.

One alternative is to fork django-autoslug 1.7.1 with this fix included: https://github.com/neithere/django-autoslug/commit/6151a0b0a6eafbcd42bce7b1d2bb6d5137fcfe58.

**Review by jhsimpson — APPROVED** [review]
:+1:

**Pull request merged**
