### PR TITLE
Problem: FITS script is outdated, refs #8647

### PR DESCRIPTION
**Pull request by jrwdunham**
Updating FITS command. Refs #8647. See https://github.com/artefactual/archivematica-fpr-tools/pull/5

### CODE REVIEW

**Comment by sevein** [comment]
@jrwdunham, I'm not sure if this is correct.
We should introduce a new migration, e.g. `0007_update_fits_command`, right?

**Review by sevein — CHANGES_REQUESTED** [review]
Sorry, we can't do this. We need a migration.

**Comment by sevein** [comment]
Things to remember:
- The fprule also needs to be versioned.
- The tmp folder inside AM shared directory should be used so the script works when nailgun runs on a remote machine.

**Comment by nickwilkinson** [comment]
[Problem: FITS script is outdated, refs #8647](https://trello.com/c/pIr1Ty2G/22-problem-fits-script-is-outdated-refs-8647)

**Comment by nickwilkinson** [comment]
[AgentArchives > merge Bentley PRs](https://trello.com/c/pTkoVwZg/17-agentarchives-merge-bentley-prs)

**Comment by nickwilkinson** [comment]
[Problem: FITS script is outdated, refs #8647 (fpr admin changes)](https://trello.com/c/pIr1Ty2G/22-problem-fits-script-is-outdated-refs-8647-fpr-admin-changes)

**Comment by nickwilkinson** [comment]
[PR 8647](https://trello.com/c/uWBWKpJ5/29-pr-8647)

**Comment by jrwdunham** [comment]
See https://github.com/artefactual/archivematica/pull/706

**Review by sevein — APPROVED** [review]

**Pull request merged**
